- name: "[java8] Ensure python-httplib2 is present for uri module"
  yum: name=python-httplib2 state=present
  when: java_version == "8" or java_version == "7-oracle"
  sudo: true
  tags: java

- name: "install java8 Oracle"
  yum: name="java-1.8.0-openjdk.x86_64" state=installed
  when: java_version == "8"
  tags: java

- name: ensure that the directory is present
  file:
    path: /usr/lib/jvm/
    state: directory
  when: java_version == "10-openjdk" or java_version == "11-openjdk"
  tags: java

- name: "[java10] Download & Uncompress tar gz file on the directory"
  unarchive:
    src: https://download.java.net/java/GA/jdk{{java10.version}}/{{java10.build_version}}/{{java10.code_version}}/{{java10.version}}/openjdk-{{java10.build_version}}_linux-{{java10.architecture}}_bin.tar.gz
    dest: /usr/lib/jvm/
    remote_src: yes
    creates: /usr/lib/jvm/jdk-{{java10.build_version}}
  when: java_version == "10-openjdk"
  tags: java

- name: "[java10] Add link for java binary"
  file:
    src: /usr/lib/jvm/jdk-{{java10.build_version}}/bin/java
    dest: /usr/bin/java10
    state: link
  when: java_version == "10-openjdk"
  tags: java

- name: "[java10] Add link for java home "
  file:
    src: /usr/lib/jvm/jdk-{{java10.build_version}}/
    dest: /usr/lib/jvm/java-1.10.0-openjdk
    state: link
  when: java_version == "10-openjdk"
  tags: java

- name: "[java11] Download & Uncompress tar gz file on the directory"
  unarchive:
    src: https://download.java.net/java/GA/jdk{{java11.version}}/{{java11.jdk_version}}/{{java11.code_GPL}}/openjdk-{{java11.build_version}}_linux-{{java11.architecture}}_bin.tar.gz
    dest: /usr/lib/jvm/
    remote_src: yes
    creates: /usr/lib/jvm/jdk-{{java11.build_version}}
  when: java_version == "11-openjdk"
  tags: java

- name: "[java11] Add link for java binary"
  file:
    src: /usr/lib/jvm/jdk-{{java11.build_version}}/bin/java
    dest: /usr/bin/java11
    state: link
  when: java_version == "11-openjdk"
  tags: java

- name: "[java11] Add link for java home "
  file:
    src: /usr/lib/jvm/jdk-{{java11.build_version}}/
    dest: /usr/lib/jvm/java-1.11.0-openjdk
    state: link
  when: java_version == "11-openjdk"
  tags: java
