- hosts: fhir-host
  connection: local
  user: root
  roles:
   - { role: java, java_version: "11-openjdk", tags: java }
   - { role: tomier, tags: tomtier }
  vars_files:
   - ['vars/env_{{ env }}.yml']
