---
keycloak_ver: '4.5.0.Final'
keycloak_mirror: https://downloads.jboss.org/keycloak

keycloak_checksums:
  # https://downloads.jboss.org/keycloak/3.2.1.Final/keycloak-3.2.1.Final.tar.gz.sha1
  '3.2.1.Final': sha1:de6d7ac62e2a82c7ecdfcf04c9970163415d9b75
  # https://downloads.jboss.org/keycloak/3.4.3.Final/keycloak-3.4.3.Final.tar.gz.sha1
  '3.4.3.Final': sha1:f2b1272ab8d4413f408b444bc2108740845bc976
  # https://downloads.jboss.org/keycloak/4.4.0.Final/keycloak-4.4.0.Final.tar.gz.sha1
  '4.4.0.Final': sha1:5a1cf11f69862ff6944267a4e5509e9afaedddcb
  # https://downloads.jboss.org/keycloak/4.5.0.Final/keycloak-4.5.0.Final.tar.gz.sha1
  '4.5.0.Final': sha1:6a5b861eed289764ff36566d353a00e38970a912

keycloak_parent_install_dir: /home/vidal

user_wildfly: wildfly
keycloak_bind_address: 0.0.0.0
keycloak_http_port: 8080
keycloak_https_port: 8443

