---
java10:
  build_version: "10.0.1"
  code_version: "fb4372174a714e6b8c52526dc134031e"
  version: "10"
  architecture: "x64"
  destination: "/usr/lib/jvm"

java11:
  build_version: "11.0.1"
  version: "11"
  jdk_version: "13"
  code_GPL: "GPL"
  architecture: "x64"
  destination: "/usr/lib/jvm"
