- name: Create symbolic link for java
  file:
    src: "/usr/lib/jvm/jdk-11.0.1/bin/java"
    dest: "/usr/bin/java11"
    state: link

- name:  copy systemd script for vira
  template:
     src: "{{ item }}.j2"
     dest: "/usr/lib/systemd/system/{{ product_name }}.service"
     mode: 0644
  with_items:
     - tomcat-systemd
  tags: tomcat_init
  notify:
     - daemon-reload
     - restart java
