- hosts: vira-host
  connection: local
  user: root
  roles:
   - { role: keycloak, tags: keycloak }
   - { role: java, java_version: "11-openjdk", tags: java }
   - { role: tomtier, tags: tomtier }
  var_files:
   - ['vars/env_{{ env }}.yml']
